name: module3_task0
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5 * * *'
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2
      - name: Validate Makefile
        run: |
          cd module3_task0
          make help
        working-directory: module3_task0
