---


name: module3_task0

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'module3_task0/**'
    schedule:
      - cron: '30 5 * * *'
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: clone github repository
        uses: action/checkout@v3

      - name: Validate Makefile
        run: |
          cd module3_task0/
          make help
        working-directory: module3_task0
