---


name: module3_task0

on:
  push:
    paths:
      - 'module3_task0/**'
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone github repository
        uses: actions/checkout@v3

      - name: Validate Makefile
        run: |
          cd module3_task0/
          make help
