---
name: release_drafter

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, master]
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    run-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
